<?php

return [
    "Preferred Equipment Group 1SD",
    "5.45 Final Drive Axle Ratio",
    "18'' Machined Aluminum Wheels",
    "Cloth w/Leatherette Seat Trim",
    "Ride & Handling Suspension",
    "Radio: 8'' Diagonal Buick Infotainment System",
    "8-Way Power Driver Seat Adjuster",
    "4-Way Manual Passenger Seat Adjuster",
    "2-Way Power Driver Lumbar Control",
    "Heated Driver & Front Passenger Seats",
    "SiriusXM Radio",
    "Enhanced Performance 6-Speaker System",
    "2 USB Ports w/Auxiliary Input Jack",
    "4-Wheel Disc Brakes",
    "6 Speakers",
    "Air Conditioning",
    "Electronic Stability Control",
    "Front Bucket Seats",
    "Front Center Armrest",
    "Spoiler",
    "Tachometer",
    "ABS brakes",
    "Automatic temperature control",
    "Bodyside moldings",
    "Brake assist",
    "Bumpers: body-color",
    "Delay-off headlights",
    "Driver door bin",
    "Driver vanity mirror",
    "Dual front impact airbags",
    "Dual front side impact airbags",
    "Front anti-roll bar",
    "Front dual zone A/C",
    "Front fog lights",
    "Front reading lights",
    "Front wheel independent suspension",
    "Fully automatic headlights",
    "Heated door mirrors",
    "Heated front seats",
    "Illuminated entry",
    "Knee airbag",
    "Low tire pressure warning",
    "Occupant sensing airbag",
    "Outside temperature display",
    "Overhead airbag",
    "Panic alarm",
    "Passenger door bin",
    "Passenger vanity mirror",
    "Power door mirrors",
    "Power driver seat",
    "Power steering",
    "Power windows",
    "Radio data system",
    "Rear seat center armrest",
    "Rear side impact airbag",
    "Rear window defroster",
    "Rear window wiper",
    "Remote keyless entry",
    "Roof rack: rails only",
    "Security system",
    "Speed control",
    "Speed-sensing steering",
    "Split folding rear seat",
    "Steering wheel mounted audio controls",
    "Telescoping steering wheel",
    "Tilt steering wheel",
    "Traction control",
    "Trip computer",
    "Variably intermittent wipers",
    "Front beverage holders",
    "Compass",
    "AM/FM radio: SiriusXM",
    "Exterior Parking Camera Rear",
    "Auto High-beam Headlights",
    "Emergency communication system: OnStar and Buick connected services capable",
    "Engine; ECOTEC 1.2L Turbo (GM-estimated 137 hp [102 kW] @ 5;000 rpm; 162 lb-ft of torque [219 Nm] @ 2;500 rpm)",
    "GVWR; 4211 lbs. (1910 kg)",
    "Keyless start; push button",
    "Engine control; stop/start system",
    "Engine control; stop/start system disable switch; non-latching",
    "Engine air filtration monitor",
    "Axle; 5.45 final drive ratio",
    "Front-wheel drive",
    "Alternator; 130 amps",
    "Trailering provisions",
    "Suspension; Ride and Handling",
    "Steering; power; variable effort; electric",
    "Brakes; 4-wheel antilock; 4-wheel disc",
    "Brakes; front and rear; electric",
    "Brake; electronic parking",
    "Capless Fuel Fill",
    "Tires; 9R225.5 133L; all-season; blackwall",
    "Wheel; spare; 16'' (40.6 cm) steel",
    "Tire; compact spare 16'' (40.3 cm); located under cargo floor",
    "Luggage rack; side rails; roof-mounted",
    "Bumper; front with Anderson Silver accents (Deleted when (GFC) Sport Touring Package is ordered.)",
    "Bumper; rear with Anderson Silver accents (Deleted when (GFC) Sport Touring Package is ordered.)",
    "Moldings; bodyside; molded color (Not available with (GFC) Sport Touring Package.)",
    "Moldings; upper side window; chrome roofline and Black beltline",
    "Shutters; front lower grille; active front",
    "Headlamps; halogen",
    "Headlamp control; automatic on and off",
    "Headlamp control; IntelliBeam auto high beam",
    "Fog lamps; front",
    "Lamp; center high-mounted stop/brake (CHMSL); LED",
    "Tail lamps; halogen",
    "Mirrors; outside heated power-adjustable; body-color; manual-folding",
    "Glass; acoustic; laminated windshield",
    "Glass; deep-tinted",
    "Windshield; solar absorbing",
    "Wipers; front intermittent with pulse washers",
    "Wiper; rear intermittent",
    "QuietTuning Buick exclusive process that consists of acoustically enhanced windshield and side glass; along with numerous noise canceling acoustic treatmen",
    "Liftgate; manual",
    "Door handles; body-color with chrome strips",
    "Door pillar trim; blackout",
    "Mechanical jack with tools",
    "Audio system feature; 6-speaker system; enhanced performance",
    "4G LTE Wi-Fi Hotspot capable (Terms and limitations apply. See onstar.com or dealer for details.)",
    "Noise control system; active noise cancellation",
    "Seat adjuster; front passenger 4-way manual",
    "Seats; heated driver and front passenger",
    "Headrests; 2-way adjustable; up/down; driver and front passenger",
    "Seatback; passenger flat-folding",
    "Knee bolster; driver and front passenger",
    "Seat; rear 60/40 split-bench; folding (60 percent on passenger side)",
    "Console; floor; with armrest",
    "Armrest; rear center",
    "Door sill plate cover; front",
    "Steering column; tilt and telescopic; adjustable",
    "Steering wheel; leather-wrapped 3-spoke; color-keyed with theft-deterrent locking feature",
    "Driver Information Center enhanced; 4.2'' multi-color display; includes tachometer; speedometer; trip odometer; fuel level; coolant temperature; oil life m",
    "Compass display",
    "Key system; 2 keys",
    "USB charging port; charging only",
    "Air conditioning; dual-zone automatic climate control with individual climate settings for driver and right-front passenger",
    "Defogger; rear-window; electric",
    "Glovebox; dual",
    "Mirror; inside rearview manual day/night with tilt",
    "Visors; driver and front passenger illuminated vanity mirrors; covered; sliding",
    "Assist handle; with coat hook; front passenger",
    "Assist handle; rear outboard",
    "Lighting; interior; dimming instrument panel cluster",
    "Lighting; interior; overhead courtesy dual reading lamp",
    "Lighting; interior; roof; rear courtesy",
    "Lighting; interior; rear cargo compartment lamp",
    "Shift knob; satin silver and chrome",
    "Map pocket; driver seatback",
    "Map pocket; front passenger seatback; lateral mesh",
    "Cargo security cover; rear",
    "Buick Connected Access capable (Subject to terms. See onstar.com or dealer for details.)",
    "StabiliTrak; stability control system",
    "Automatic Emergency Braking",
    "Front Pedestrian Braking",
    "Brake lining wear indicator",
    "Daytime Running Lamps; Signature LED",
    "Airbags; frontal and knee for driver and front passenger; seat-mounted side-impact and head-curtain for front and rear seating positions (Always use seat b",
    "Airbag; Passenger Sensing System; sensor indicator inflatable restraint; front passenger/child presence detector (Always use seat belts and child restraint",
    "OnStar and Buick connected services capable (Terms and limitations apply. See onstar.com or dealer for details.)",
    "Lane Change Alert with Side Blind Zone Alert",
    "Rear Cross Traffic Alert",
    "Forward Collision Alert",
    "Following Distance Indicator",
    "Seat belt; 3-point; driver with load limiter; height adjustable",
    "Seat belt; 3-point; front passenger with load limiter; height adjustable",
    "Seat belts; 3-point; rear; all seating positions",
    "LATCH system (Lower Anchors and Tethers for CHildren) for child restraint seats; second row; 2 lower anchors for outboard seating positions only; 3 top tet",
    "Door locks; rear child security",
    "Teen Driver a configurable feature that lets you activate customizable vehicle settings associated with a key fob; to help encourage safe driving behavior.",
    "Tire Fill Alert (Does not monitor spare tire.)",
    "Tire Pressure Monitoring System; manual learn (Does not monitor spare tire.)",
];

?>
